# Generated by Django 2.0.1 on 2018-01-28 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='LocationSync',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=30)),
                ('longtitude', models.CharField(max_length=30)),
                ('sync_time', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apis.LocationSync'),
        ),
    ]
